LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := HManager
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := HManager.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_CERTIFICATE := PRESIGNED

include $(BUILD_PREBUILT)